//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndromedaRentCar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int IdClientes { get; set; }
        public string Nombre { get; set; }
        public string Cedula { get; set; }
        public string NoTarjetaCredito { get; set; }
        public Nullable<int> LimiteCredito { get; set; }
        public string TipoPersona { get; set; }
        public Nullable<bool> Estado { get; set; }
    }
}
