//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndromedaRentCar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspeccion
    {
        public int IdInspeccion { get; set; }
        public Nullable<bool> Ralladuras { get; set; }
        public string CantCombustible { get; set; }
        public Nullable<bool> GomaRepuesto { get; set; }
        public Nullable<bool> Gato { get; set; }
        public Nullable<bool> RoturaCristal { get; set; }
        public Nullable<bool> GomasDelanteras { get; set; }
        public Nullable<bool> GomasTraseras { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<bool> Estado { get; set; }
        public int IdVehiculo { get; set; }
        public int IdCliente { get; set; }
        public int IdEmpleado { get; set; }
    }
}
